apiVersion: apps/v1
kind: Deployment
metadata:
  name: freelance-deployment
  namespace: freelance
spec:
  replicas: 1
  selector:
    matchLabels:
      app: freelance
  template:
    metadata:
      labels:
        app: freelance
    spec:
      containers:
        - name: freelance
          image: waheedgulzar51/freelance:latest
          ports:
            - containerPort: 5000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: freelance-secret
                  key: DATABASE_URL
