apiVersion: v1
kind: Service
metadata:
  name: freelance-service
  namespace: freelance
spec:
  type: NodePort  
  selector:
    app: freelance
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30036  
