name: Build and Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Start Minikube
      run: minikube start

    - name: Configure Docker to use Minikube
      shell: powershell
      run: |
          & minikube -p minikube docker-env --shell powershell | Invoke-Expression

    - name: Build Docker image
      run: |
        docker build -t waheedgulzar51/freelance:latest .

    - name: Login to Docker Hub
      run: |
        docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"
        
    - name: Push Docker image to Docker Hub
      run: docker push waheedgulzar51/freelance:latest

    - name: Deploy to Minikube
      run: |
        kubectl apply -f deployment.yml
        kubectl apply -f service.yml
